---
version: '3'

services:
    java:
        build:
            context: ./java
            dockerfile: java.Dockerfile
        volumes:
            - myapp:/javaapp/war-web-project/target

    tomcat:
        build:
            context: ./tomcat
            dockerfile: tomcat.Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - myapp:/opt/tomcat/webapps
        depends_on:
            - java

volumes:
    myapp: